#!/bin/sh

# Copy to .git/hooks, rename pre-commit, add any protected text you want to prevent getting commited
# Modify this
# LIST='list\|of\|words\|splitted\|by\|slash\|and\|pipe'
LIST="YOUR_SECRET\|ANOTHER_SECRET"

if git rev-parse --verify HEAD >/dev/null 2>&1; then
    against=HEAD
else
    against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
fi

for FILE in `git diff-index --name-status --cached $against -- | cut -c3-` ; do
    # Check if the file contains one of the words in LIST
    if grep -w $LIST $FILE; then
      echo $FILE." has one of the word you don't want to commit. Please remove it"
      exit 1
    fi
      done
exit